server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    connection-timeout: 120000

logging:
  level:
    root: info

spring:
  profiles:
    active: local # 사용할 프로파일 지정

management:
  endpoints:
    web:
      exposure:
        include: health, info  # 필요한 엔드포인트만 노출
  endpoint:
    health:
      show-details: never      # 상세 정보는 보안상 숨김