server:
  servlet:
    context-path: /consumer
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    connection-timeout: 120000

logging:
  level:
    root: info
    org.springframework.security.web.FilterChainProxy: debug
    org.hibernate.type.descriptor.sql: trace

spring:
  profiles:
    active: local # 사용할 프로파일 지정

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration # springboot default 몽고디비 자동설정 비활성화 
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration # springboot default 몽고디비 자동설정 비활성화

  h2:
    console:
      enabled: false

  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    open-in-view: false
    show-sql: false
    format-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        cache:
          usesecondlevelcache: true
          usequerycache: false
          region:
            factoryclass: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
        generatestatistics: true

management:
  endpoints:
    web:
      exposure:
        include: health, info  # 필요한 엔드포인트만 노출
  endpoint:
    health:
      show-details: never      # 상세 정보는 보안상 숨김