server:
  port: 8000

mqtt:
  broker: tcp://localhost:1883
  client-id: mqtt-kafka-producer
  topic: test/mqtt

spring:
  config:
    activate:
      on-profile: dev

  devtools:
    livereload:
      enabled: true

  kafka:
    consumer:
      group-id: vehicle-consumer-group
      bootstrap-servers: localhost:19092,localhost:19093,localhost:19094
      auto-offset-reset: earliest
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
      